### ISSUE TITLE
当最新版的微信开发者工具开启“上传时进行代码保护”时报错

### ISSUE THREAD

**Issue by lnlion** [IdanLoo/minapp-promise#1]
按照文档正常引用了minapp-promise; 但当开启“上传时进行代码保护”，然后上传代码时，编辑器会报错；报错内容详见截图
![image](https://user-images.githubusercontent.com/2811986/51896255-ffa58a80-23e6-11e9-845c-723ce0278322.png)

**Comment by siwei-lu** [comment]
抱歉这么久才回复，我这个年假放得比较久。
您反馈的问题在 0.1.0 版本已解决，谢谢支持。

**Comment by xiaomizhou66** [comment]
这个问题解决了？已经没有吧，我用的还是错误的，错了怎么办

**Comment by xiaomizhou66** [comment]
有人回答这个问题么？选择代码保护的话会报错的，

**Comment by siwei-lu** [comment]
@xiaomizhou66 请先在你的 package.json 中确认 minapp-promise 是最新的 0.1.0 版本。如果还是不行的话，请提供代码和错误的截图以供我排查问题。谢谢。
